### ISSUE TITLE
Export user's makes into JSON hosted on S3

### ISSUE THREAD

**Issue by simonwex** [mozilla/MakeAPI#241]
As a part of [archiving](https://blog.webmaker.org/whats-next-for-webmaker-tools) user's makes:

For each user, create a JSON file with all of the user's makes, upload file to S3 in a user-space URL. (e.g. /archivedMakes/{user_id}.json

```JSON
{
  makes: [
    {
      email: "fake@123.com",
      url: "http://notarealurl.com/make_asdf.html",
      contentType: "application/x-applicationName",
      title: "title of make",
      contenturl: "http://realMakeURL.com/notbehindaproxy",
      locale: "en_CA",
      description: "description of make",
      thumbnail: "http://fakeimageURL.com/img123.gif",
      author: "anonymous person",
      tags: [
          "foo",
          "bar"
      ],
      remixedFrom: "OBJECT-ID-OF-ANOTHER-MAKE"
    },
    ...
  ]
  total: n
}
```

**Comment by simonwex** [comment]
@cadecairos could you help me jam on this^ I think it could use some tweaks to be more useful.

**Comment by cadecairos** [comment]
We could dump the mongo db with [mongodump](http://docs.mongodb.org/manual/reference/program/mongodump/), providing a query to limit the output (not deleted, [group by username](http://docs.mongodb.org/manual/reference/operator/aggregation/group/)), and then process the BSON file in with the [bson](https://www.npmjs.com/package/bson) module, and create the files we want on S3

**Comment by cadecairos** [comment]
Okay, I've been messing around with this all day and I think I know What we need to do:

1. Use mongo's aggregation pipeline (must check compatibility - I'm running v3, but we probably are on v2.6 on staging/prod) to group makes by email, and output into a new collection

```js
db.makes.aggregate([
  {
    $group: {
      _id: {
        email: "$email"
      },
      makes: {
        $push: {
          id: "$_id.oid",
          contentType: "$contentType",
          createdAt: "$createdAt",
          description: "$description",
          editurl: "$editurl",
          email: "$email",
          locale: "$locale",
          remixedFrom: "$remixedFrom",
          remixurl: "$remixurl",
          thumbnail: "$thumbnail",
          title: "$title",
          updatedAt: "$updatedAt",
          url: "$url"
        }
      }
    }
  }, {
    $match: {
      deletedAt: { $eq: null }
    }
  }, {
    $out: "aggregated_makes"
  }
]);
```

2. use `mongoexport` to get that data into a file:

```shell
mongoexport --jsonArray --db makeapi --collection aggregated_makes --out aggregated_makes.json
```

3. write a script to process that file, getting webmaker username for each email, and outputting each group  of makes to S3 as a new json file `<username>.json`

**Comment by simonwex** [comment]
@cadecairos this would let anyone see people's email address based on their username, no? (PII leak)

**Comment by cadecairos** [comment]
@simonwex I didn't plan on keeping email in the final json we upload to S3 - we're going to need to get the username given the email sitting in mongodb, and transform make data to not contain emails

**Comment by jbuck** [comment]
@cadecairos Awesome!

We'll need to process the email addresses into usernames as a post-processing step, but I think this is a good move since we won't need to code two versions of the /me tool, one for MakeAPI and one for static data.

**Comment by cadecairos** [comment]
So, today we learned we're running mongodb 2.4 in staging and production (FML)

This means a couple things:

1. No $out stage in the aggregation pipleline. tldr; we can't pipe aggregation results to a new collection.

2. No ability to remove limits on disk usage when building the new set of documents. It looks like we're being capped at 16MB. Compare this to the 23.1MB makes collection on staging and 460MB collection on production
